START TRANSACTION;

create table orders
(
    id                bigint generated by default as identity
        constraint "PK_orders"
            primary key,
    external_id       uuid                     not null,
    weight            bigint                   not null,
    collection_date   timestamp with time zone not null,
    shipper_town      text                     not null,
    consignee_town    text                     not null,
    shipper_address   text                     not null,
    consignee_address text                     not null
);

INSERT INTO orders (id, external_id, weight, collection_date, shipper_town, consignee_town, shipper_address, consignee_address) VALUES (11, 'c299c6d6-4a3c-4069-ab52-8f473108b411', 1000, '2024-06-23 21:00:00.000000 +00:00', 'Санкт-Петербург', 'Москва', 'Скачков переулок, 5', 'Большая Никитская улица, 13/6');
INSERT INTO orders (id, external_id, weight, collection_date, shipper_town, consignee_town, shipper_address, consignee_address) VALUES (12, '8eb8a777-ec5f-41fd-8823-f7b70d73e3cb', 1100, '2024-06-22 21:00:00.000000 +00:00', 'Санкт-Петербург', 'Москва', 'проспект Славы, 31', 'улица Высоцкого, 3с1');
INSERT INTO orders (id, external_id, weight, collection_date, shipper_town, consignee_town, shipper_address, consignee_address) VALUES (13, 'eed599b0-1da8-47f3-9898-509b04aba0d7', 800, '2024-06-22 21:00:00.000000 +00:00', 'Москва', 'Санкт-Петербург', '2-й Щемиловский переулок, 16-20', 'Средний проспект Васильевского острова, 57');
INSERT INTO orders (id, external_id, weight, collection_date, shipper_town, consignee_town, shipper_address, consignee_address) VALUES (14, 'c9b8a211-bdc1-4979-990a-e81eea8fd372', 800, '2024-06-24 21:00:00.000000 +00:00', 'Москва', 'Санкт-Петербург', 'улица Орджоникидзе, 11', '15-я линия Васильевского острова, 4-6');


COMMIT;