// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20240625092237_AddOrders")]
    partial class AddOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Database.Entities.OrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collection_date");

                    b.Property<string>("ConsigneeAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consignee_address");

                    b.Property<string>("ConsigneeTown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consignee_town");

                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<string>("ShipperAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipper_address");

                    b.Property<string>("ShipperTown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipper_town");

                    b.Property<long>("Weight")
                        .HasColumnType("bigint")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("orders", "ordersdb");
                });
#pragma warning restore 612, 618
        }
    }
}
